version: '3.8'

services:
  # API - catApi
  cat-api:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    command: sh -c "pip install --upgrade pip && pip install prometheus_client urllib3==1.26.6 requests fastapi uvicorn prometheus-client && python worker.py && uvicorn cat_api:app --host 0.0.0.0 --port 8000"
    environment:
      - LOG_LEVEL=INFO
      - CAT_API_KEY="<SUA_API_KEY_AQUI>"
    restart: unless-stopped
    networks:
      - monitoring

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - cat-api

  # Grafana para apresentacao dos dados de observabilidade
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/usr/share/grafana/conf/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

  # Loki para logs
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - monitoring

  # Promtail para coletar logs e enviar ao Loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - loki

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: