server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: cat-api
  static_configs:
  - targets:
      - localhost
    labels:
      job: cat-api
      __path__: /app/logs/catapi.log
      env: production
  
  pipeline_stages:
    - json:
        expressions:
          time:
          level:
          message:
          service:
          endpoint:
          method:
          status:
          latency:
          client:
    - labels:
        level:
        service:
        endpoint:
        method:
        status:
    - timestamp:
        source: time
        format: RFC3339