{
 "title": "Cat API Monitoring",
 "description": "Dashboard para monitoramento da Cat API",
 "tags": [
  "monitoring",
  "api"
 ],
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "endpoint", "query": { "query": "label_values(endpoint)" } },
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Metricas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count - Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(request_count_total{job=\"cat-api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (rate(request_latency_seconds_bucket{endpoint!~\"/metrics|/metrics/|/breeds/acur|doc|/redocs|docs|/favicon.ico|/openapi.json|/|Value\"}[$__interval])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(job) (rate(request_latency_seconds_count{job=\"cat-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "API Logs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(job) (rate({job=\"cat-api\"} [$__auto]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cat-api\", endpoint!~\"/|/metrics|/metrics/|/health|/docs|/favicon\\\\.ico|/openapi\\\\.json|/redocs\"}"
    }
   ]
  },
  {
   "title": "API Logs - Requisições com erro",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cat-api\", endpoint!~\"/breeds/:breeds_id|/metrics|/metrics/|/favicon\\\\.ico|/docs|/openapi\\\\.json|/redocs\"} | status != `200` | level != `INFO`",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cat Api - Resquest por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (rate({job=\"cat-api\", endpoint!~\"/|/breeds/:breeds_id|/docs|/metrics|/metrics/|/openapi\\\\.json|/health|/favicon\\\\.ico\"} [$__auto]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cat Api - Latencia por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (rate({job=\"cat-api\"} [$__auto]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cat Api - % Severidades",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({job=\"cat-api\"} [$__auto]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cat Api - Endpoint x status code",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status, endpoint) (\n  count_over_time(\n    {job=\"cat-api\"} \n    | json \n    | status != \"\"\n    [$__interval]\n  )\n)\n",
     "legendFormat": "{{endpoint}} com status {{status}}"
    }
   ]
  }
 ]
}